name: Deploy static site to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/configure-pages@v3
      - name: Build site
        run: |
          mkdir _site
          cp -r site/* _site/
      - uses: actions/upload-pages-artifact@v1
        with:
          path: _site
      - uses: actions/deploy-pages@v2
        with:
          wait-for-deployment: true
